from tetris.constants import TETRIS_FIELD_COLS, TETRIS_FIELD_ROWS, TILE_SIZE

DISPLAY_WIDTH = 4 * (TETRIS_FIELD_COLS + 6) * TILE_SIZE
DISPLAY_HEIGHT = (TETRIS_FIELD_ROWS + 2) * TILE_SIZE

FPS: int = 60
